services:
  fastapi:
    image: seungkyu/cafe_crawl_fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    networks:
      - seungkyu

networks:
  seungkyu:
    driver: bridge
