name: CICD 설정

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}

  pull_image_and_deploy:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: transfer docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: "${{ secrets.SSH_DIR }}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_DIR }}
            docker-compose down
            docker image rm -f ${{ secrets.DOCKER_IMAGE_NAME }} || true
            docker-compose pull
            docker-compose up -d